apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
spec:
  selector:
     app: twittertrend
  type: ClusterIP
  ports:
  - name: http
    port: 8001
    targetPort: 8000
    protocol: TCP


