apiVersion: apps/v1
kind: Deployment
metadata:
  name: twittertrend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twittertrend
  template:
    metadata:
      labels:
        app: twittertrend
    spec:
      containers:
      - name: twittertrend
        image: stalin/twittertrend:1.3
        ports:
        - containerPort: 8000
        env:
        - name: CONSUMER_KEY
          valueFrom: 
            secretKeyRef:
              name: mysecret
              key: CONSUMER_KEY
        - name: CONSUMER_SECRET
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: CONSUMER_SECRET
        - name: ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: ACCESS_TOKEN
        - name: ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: ACCESS_TOKEN_SECRET

