apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  CONSUMER_KEY: HpwdfLFZLON0mT8BLWSSYfTxs
  CONSUMER_SECRET: 
  ACCESS_TOKEN: 19703354-wbDGYDsZAIRQKNwPRRQqX3bUkvtLVxoHrGMpkDeCG
  ACCESS_TOKEN_SECRET: 
