apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  CONSUMER_KEY: HpwdfLFZLON0mT8BLWSSYfTxs
  CONSUMER_SECRET: 0FKwKj0GuPMz50dYTYQ3EQxqHfSyNsxipyfPGgXemMHkfWuR3G
  ACCESS_TOKEN: 19703354-wbDGYDsZAIRQKNwPRRQqX3bUkvtLVxoHrGMpkDeCG
  ACCESS_TOKEN_SECRET: 2pu202TQ9D1nZUVy77kyN9kfaLtJ6lBxWweW3jddTmVMN
